name: GitPortfolio
description: Opinionated template engine analysing your GitHub profile and repositories
author: George-Andrei Iosif
branding:
  icon: user
  color: gray-dark
inputs:
  config:
    description: Configuration file
    required: true
  pat:
    description: GitHub PAT
    required: true
  cache:
    description: Cache folder
    required: false
    default: './cache'
  datasources:
    description: Custom datasources folder
    required: true
  template:
    description: Template file
    required: true
  output:
    description: Output file
    required: true
  update:
    description: Boolean indicating if the configuration should be updated
    required: false
    default: "false"
runs:
  using: 'composite'
  steps:
    - name: Clones the latest version of GitPortfolio
      uses: actions/checkout@v4
      with:
        repository: iosifache/gitportfolio
        path: ./gitportfolio
    - name: Installs GitPortfolio
      shell: bash
      run: pip install ./gitportfolio
    - name: Run GitPortfolio
      shell: bash
      env:
        GITHUB_PAT: ${{ inputs.pat }}
      run: |
        args=()

        if [[ "${{ inputs.update }}" = "true" ]]; then
            args+=(--update)
        fi

        gitportfolio                               \
          --config ${{ inputs.config }}            \
          --cache ${{ inputs.cache }}              \
          --datasources ${{ inputs.datasources }}  \
          --template ${{ inputs.template }}        \
          --output ${{ inputs.output }}            \
          "${args[@]}"                             \
          2>/dev/null
